name: Build and Deploy Docker Image

# Trigger the workflow on push to the main or master branch, or on pull requests targeting main or master
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for building multi-platform Docker images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker image to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-java-app:latest,mode=max

    # Optional: Tag image with commit SHA
    - name: Tag Docker image with commit SHA
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest ${{ secrets.DOCKER_USERNAME }}/my-java-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/my-java-app:${{ github.sha }}


