name: Publish Docker image

on:
  push:
    branches:
      - master   # Trigger on push to the master branch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repo
    - name: Check out the repo
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .  # The context is the root of your repository
        push: true   # Push the image to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest  # Tag the image
        file: ./Dockerfile  # Explicitly specify the Dockerfile path if it's not in the root
