name: Debug and Build Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Debug - List files and check Dockerfile existence
    - name: Debug - List all files in the repository
      run: |
        echo "Listing all files in the repository root..."
        ls -la
        echo "Searching for Dockerfile recursively..."
        find . -name "Dockerfile"

    # Step 3: Exit if Dockerfile not found
    - name: Validate Dockerfile existence
      run: |
        echo "Validating Dockerfile existence..."
        if [ ! -f Dockerfile ]; then
          echo "Error: Dockerfile not found in the repository root!";
          exit 1;
        fi

    # Step 4: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 5: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .  # Adjust if Dockerfile is not in the root directory
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
