name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Debug - Check if the Dockerfile exists in the repository
    - name: Check Dockerfile existence
      run: |
        echo "Checking if Dockerfile exists..."
        ls -la # List files to confirm Dockerfile location
        if [ -f Dockerfile ]; then echo "Dockerfile found!"; else echo "Dockerfile not found!"; fi

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .  # Root directory of the repository
        file: ./Dockerfile  # Path to the Dockerfile (assumes Dockerfile is in the root)
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-java-app:latest,mode=max

    # Optional: Tag the image with commit SHA
    - name: Tag Docker image with commit SHA
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest ${{ secrets.DOCKER_USERNAME }}/my-java-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/my-java-app:${{ github.sha }}
